"""Replace YouTube with PodcastIndex

Revision ID: 5812393d324d
Revises: 7de2475b6cef
Create Date: 2025-09-28 21:49:27.183878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5812393d324d'
down_revision: Union[str, Sequence[str], None] = '7de2475b6cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_youtube_video_id'), table_name='episodes')
    op.drop_column('episodes', 'youtube_video_id')
    op.add_column('podcasts', sa.Column('podcast_index_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_podcasts_youtube_channel_id'), table_name='podcasts')
    op.create_index(op.f('ix_podcasts_podcast_index_id'), 'podcasts', ['podcast_index_id'], unique=True)
    op.drop_column('podcasts', 'youtube_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('youtube_channel_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_podcasts_podcast_index_id'), table_name='podcasts')
    op.create_index(op.f('ix_podcasts_youtube_channel_id'), 'podcasts', ['youtube_channel_id'], unique=True)
    op.drop_column('podcasts', 'podcast_index_id')
    op.add_column('episodes', sa.Column('youtube_video_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_episodes_youtube_video_id'), 'episodes', ['youtube_video_id'], unique=False)
    # ### end Alembic commands ###
